# Generated by Django 5.0.7 on 2024-08-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('warehouse', 'product')},
        ),
    ]
