# Generated by Django 5.1 on 2024-08-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
